### ISSUE TITLE
Use InfluxDB as volume usage metrics provider

### ISSUE THREAD

**Issue by aleksrosz** [topolvm/pvc-autoresizer#115]
**What should the feature do:**
Add possibility to use InfluxDB  as volume usage metrics provider

**What is use case behind this feature:**
Some people use InfluxDB for monitoring and it can be useful.

**Comment by aleksrosz** [comment]
Maybe I will look how to do this because it is useful in my case. But maybe someone already did that or it is in progress.

**Comment by satoru-takeuchi** [comment]
Unfortunately, we don't have a plan to support InfluxDB for now.

**Comment by satoru-takeuchi** [comment]
I close this ticket for now.
