### ISSUE TITLE
Resizing for a pvc gets stuck in the "volume storage limit reached" condition of resize method even if it has plenty of capacity.

### ISSUE THREAD

**Issue by kkburr** [topolvm/pvc-autoresizer#118]
**Describe the bug**
[Relevant code](https://github.com/topolvm/pvc-autoresizer/blob/main/runners/pvc_autoresizer.go#L198-L202)

```
	if cap.Cmp(limitRes) >= 0 {
		log.Info("volume storage limit reached")
		metrics.ResizerLimitReachedTotal.Increment(pvc.Name, pvc.Namespace)
		return nil
	}
```

I recently had a pvc that was resized and [logged ](https://github.com/topolvm/pvc-autoresizer/blob/main/runners/pvc_autoresizer.go#L221) the following values:
```
{
   threshold: 159799119052
   available: 1054669107200
   inodesThreshold: 6612582
   inodesAvailable: 0
}
```

Since the `inodesThreshold` was reported as being higher than `vs.AvailableInodeSize` ([link](https://github.com/topolvm/pvc-autoresizer/blob/main/runners/pvc_autoresizer.go#L204)) it resized, but when I tracked down the metrics in our Prometheus instance, the value for inodesAvailable was actually 66125287.

After our PVC resized, it now had matching values for `metadata.annotations.resize.topolvm.io/storage_limit` and `spec.resources.request.storage`, so it returned true for `if cap.Cmp(limitRes) >= 0`. However, it was actually using ~1% of available bytes.

I'm wondering if this is a common occurrence, that a resize it triggered unnecessarily. If so, would it be useful to have `pvc.Spec.Resources.Requests[corev1.ResourceStorage]` more accurately reflect usage, especially if the condition `threshold > vs.AvailableBytes || inodesThreshold > vs.AvailableInodeSize` returns false on a subsequent loop?

**Environments**
- Saw same behavior on versions 0.3.0 and 0.3.1
- OS: docker

**To Reproduce**
I have not yet reproduced this in a test environment, but I could if needed.

**Expected behavior**
Since there was ~99% of capacity available on the PVC, I never would have expected the metric `pvcautoresizer_limit_reached_total` to have been incremented.

**Comment by daichimukai** [comment]
The logs indicate that the resizing appears to have occurred because the number of available inodes fell below a threshold. From which metrics did you track down the number of available inodes? pvc-autoresizer uses `kubelet_volume_stats_inodes_free`. If you also looked up this metrics, pvc-autoresizer might failed to get correct metrics value for some reason.

Could you show me the manifest of PVC? Especially, I'd like to see concrete values of annotations for pvc-autoresizer.

**Comment by kkburr** [comment]
@daichimukai The annotations I currently had on the PVC at the time were:
```
         pv.kubernetes.io/bind-completed: yes
         pv.kubernetes.io/bound-by-controller: yes
         resize.topolvm.io/increase: 15%
         resize.topolvm.io/pre_capacity_bytes: 1065327460352
         resize.topolvm.io/storage_limit: 1Ti
         resize.topolvm.io/threshold: 15%
         volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
         volume.kubernetes.io/storage-resizer: kubernetes.io/aws-ebs
 ```
  In the spec, the value for resources.requests.storage was also 1Ti.
  
 This screenshot captures the values for `kubelet_volume_stats_inodes_free`. As you can see there was a blip in metrics around 14:07, but the resizing log message wasn't actually fired until 14:17:
<img width="1502" alt="Screen Shot 2022-05-06 at 10 30 31 AM" src="https://user-images.githubusercontent.com/4874983/167210997-a1410a43-c8be-465a-8571-169a7d6c6c00.png">

**Comment by kkburr** [comment]
I actually don't see any other resize log messages for that pvc in the last 90 days, but I see that its capacity was 762Gi on Feb 24th and 877Gi Mar 10, so it must have happened occasionally. Definitely not continuously.

**Comment by daichimukai** [comment]
https://github.com/topolvm/pvc-autoresizer/blob/1d55dd8a634789d97776a4aa5adf2336d435078b/runners/metrics_client.go#L77-L93

If pvc-autoresizer failed to retrieve metrics from prometheus,  it uses zero value (i.e. `0`) instead. This might cause unintentional resize. We will fix this issue. Thanks.
