### ISSUE TITLE
ArgoCD sync trying convert 87600h0m0s back to 87600h

### ISSUE THREAD

**Issue by kfirfer** [topolvm/pvc-autoresizer#190]
Hello

Im using argocd to deploy pvc-autoresizer
In argocd sync the certificate get into the cluster with the duration parameter as 
`duration: 87600h0m0s`
Instead
`duration: 87600h`

What it means that the application in argo is always in a "not synced" state
Same goes to controller certificate

I guess to overcome it need to set minutes and seconds in the value in helm chart 

Image attached:

![Screenshot from 2023-04-05 11-41-26](https://user-images.githubusercontent.com/7741545/230028849-adea48dc-da26-4ef1-b855-d7c029a86e0b.png)

**Comment by llamerada-jp** [comment]
Hi,
I got the same problem. This is because of ArgoCD's problem. And an issue had been written. You can resolve it with the solution below.
https://github.com/argoproj/argo-cd/issues/6008#issuecomment-1346433001
