### ISSUE TITLE
Generating certificates without a cert-manager

### ISSUE THREAD

**Issue by tropnikovvl** [topolvm/pvc-autoresizer#223]
Hello.
My cluster does not have a cert-manager and it is quite inconvenient to manually generate certificates for this application.
Is it possible to do auto-generation similar to how it is done in [this chart](https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/templates/_helpers.tpl#L93)?
Thank you

**What should the feature do:**
Automatically create a certificate for a webhook in the absence of a cert-manager

**What is use case behind this feature:**
There is no need to install extra applications in the cluster and support them (cert-manager)

**Comment by toshipp** [comment]
No, such a function does not exist now. But, it is possible to implement using genCA and genSignedCert, IMO.
https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/templates/_helpers.tpl#L109-L110

If you send a PR, we are welcome to review it.

**Comment by pluser** [comment]
closed via https://github.com/topolvm/pvc-autoresizer/pull/226
