### ISSUE TITLE
Option to deploy additional prometheus resource

### ISSUE THREAD

**Issue by tobmad** [topolvm/pvc-autoresizer#231]
**What should the feature do:**
Add option to deploy the minimal needs for a prometheus resource.
Could be done with a prometheus resource using prometheus operator and crd, or enabling extra resource definitions.

**What is use case behind this feature:**
Sometimes you may want a dedicated prometheus for operations in case of failures.
With the addition of podMonitor resources there is already some assumption of available CRDs

**Comment by pluser** [comment]
Thanks for your feature request.

Is it correct that you want changes to add podMonitor resources?

**Comment by pluser** [comment]
You mean the Prometheus resources of the Prometheus Operator, correct?
I feel that a variety of measures can be taken in each environment for deploying Prometheus. Furthermore, I would like to avoid including prometheus resources in the pvc-autoresizer, as this would increase maintenance costs.

**Comment by tobmad** [comment]
Correct.
The other option I suggested was to allow extra resource definitions in general, then it is up to the developer.

**Comment by pluser** [comment]
I am not very impressed with allowing general resource definitions to be introduced.
I can't see rational reasons why they should be introduced into pvc-autoresizer instead of deploying them independently.

**Comment by tobmad** [comment]
To have a standalone helm chart, currently pvc-autoresizer depends on a Prometheus being deployed somewhere else. I find it a bit annoying to have an extra deploy, just for single Prometheus, when it could easily be made into a standalone helm chart.

You may not need a dedicated prometheus for small clusters, but when scaling a common Prometheus can be a huge point of failure. Especially when it can cause out of disk problems.

I would think allowing extra resource definitions would be maintenance free and allows users to solve many other problems, e.g. creating a storage class.

**Comment by pluser** [comment]
Thank you for your suggestion.
I think it is not a good idea to treat helm charts in an abusive way and allow them to include resources that have little relevance to pvc-autoresizer.
I believe those resources should be introduced independently.
