### ISSUE TITLE
Notification about changing the size of the PVC

### ISSUE THREAD

**Issue by tropnikovvl** [topolvm/pvc-autoresizer#234]
Hello!

It would be great if the pvc-autoresizer could send webhooks when the PVC size was successfully changed or changes were unsuccessful, perhaps another option.

Or you can go a slightly different way and make metrics with the number of successful and unsuccessful change attempts, which could be collected by Prometheus and assigned alerts to them.

**Comment by peng225** [comment]
Hi @tropnikovvl 

pvc-autoresizer has the Prometheus metrics named `pvcautoresizer_success_resize_total` and `pvcautoresizer_failed_resize_total`, which shows the number of successfull and failed resize.
https://github.com/topolvm/pvc-autoresizer?tab=readme-ov-file#prometheus-metrics

Does it meet your request?

**Comment by tropnikovvl** [comment]
Hello @peng225 !
Yes, this completely solves my problem.
Thank you!
