### ISSUE TITLE
Support Prometheus agent mode

### ISSUE THREAD

**Issue by tropnikovvl** [topolvm/pvc-autoresizer#235]
Hello.

At the moment, the pvc-autoresizer only supports Prometheus in its default operating mode. Unfortunately, in this mode it is very, very resource-hungry on large installations.

It would be great if the pvc-autoresizer could work with Prometheus in agent mode. https://prometheus.io/blog/2021/11/16/agent/

**Comment by cupnes** [comment]
Investigations are currently underway. Please wait for a while.

**Comment by cupnes** [comment]
Thank you for waiting.

The pvc-autoresizer sends queries to the prometheus. The agent mode cannot process queries by itself. So pvc-autoresizer cannot work with the agent mode.

**Comment by tropnikovvl** [comment]
Hi @cupnes!

It is sad.

Is it possible to make the pvc-autoresizer independently collect metrics from kube-state-metrics?
Then it will be independent of the monitoring tool in the end (prometheus\prometheus-agent\grafana-agent\vmagent\etc).

**Comment by cupnes** [comment]
@tropnikovvl 
We Investigated the way to get metrics from Kubelet directory at the first time of design. At that time, we found it is more complicated to implement than using Prometheus. Also, we thought that Prometheus (or software compatible with it like VictoriaMetrics) would be used in clusters large enough to require pvc-autoresizer.

After that, [attempts to make changes have been abortive](https://github.com/topolvm/pvc-autoresizer/pull/193).

**Comment by tropnikovvl** [comment]
Hello @cupnes!

Thanks for the info.

I am aware that Kubernetes will reduce the number of metrics, or rather, they plan to gradually remove the CAdvisor, but Kubernetes itself and its metrics remain.
That’s why I proposed using kube-state-metrics as a tool that itself collects all the metrics from the kubelet and is updated in accordance with its changes, the pvc-autoresizer can only go to its `/metrics` and pick up the necessary information.

Regarding monitoring in clusters, many people have been working for several years to simplify monitoring and break it down into components that will consume less resources.
For example

- “Agent” mode in Prometheus.
- Creating a Grafana Agent.

In Victoria Metrics, it’s also not possible to simply connect to the API (like prometheus) for a request, because in the clusters there are only minimal agents that send information to the central backend, which can be (and most often is) in another cluster.

Thus, continuing to support only the resource-intensive Prometheus is not always convenient to work with your application.

As an example, now, in addition to the main monitoring, I have to keep kube-state-metrics and Prometheus turned on for your application to work.

In any case, I am very grateful to you for this application! And I hope that it will only get better and less dependent on external components.

**Comment by cupnes** [comment]
Thank you. This issue was closed.
