### ISSUE TITLE
Cannot work prometheus metrics

### ISSUE THREAD

**Issue by ErdemERDOLU** [topolvm/pvc-autoresizer#243]
**Describe the bug**

**Environments** kubernetes
- Version: v1.27.7
- OS: Azure Kubernetes 

We make all the definitions and installations according to the documentation, enter the scrape configuration specified in the documentation, but it gets dropped in service discovery.
Configuration information is as below.

**Prometheus scrape configuration :** 
      - job_name: "topolvm"
        follow_redirects: false
        scheme: http
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ["pvc-autoresizer"]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: keep
            regex: node
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: ${1}:${2}
            target_label: __address__
          - source_labels: [__address__]
            action: replace
            regex: ([^:]+)(?::\d+)?
            replacement: ${1}
            target_label: instance
      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics
          - source_labels: [__name__]
            action: drop
            regex: kubelet_runtime_operations_duration_seconds.*

This is logs : {"level":"info","ts":"2024-02-28T10:21:33Z","logger":"pvc-autoresizer","msg":"failed to get volume stats","namespace":"pvc-deneme","name":"qa-mysql-pvc"}       

![image](https://github.com/topolvm/pvc-autoresizer/assets/48557863/5799b45e-3bb4-433c-be9b-5f72b47f2f26)

**Comment by pluser** [comment]
Hello.
Is the PVC bound to the Pod?
The current pvc-autoresizer does not work for unbound PVCs.
https://github.com/topolvm/pvc-autoresizer/blob/a73a201ad7aea8058d46238f6d16891e8a86e0c4/internal/runners/pvc_autoresizer.go#L143-L152
