### ISSUE TITLE
Align formatting of annotations

### ISSUE THREAD

**Issue by fad3t** [topolvm/pvc-autoresizer#248]
## What

This may sound a bit stupid, but I'm wondering if we could align the formatting of the different annotations.
Some use hyphens (`inodes-threshold`, `initial-resize-group-by`, ..) while other use underscores (`storage_limit`, `pre_capacity_bytes`), which can be confusing.
The standard seems to be hyphens from what I've seen.

## How

Update the few annotations that use underscores and replaces them with hyphens.
We might want to support both for some time to avoid breaking changes?

If you're OK with the idea, I'd be happy to contribute.

**Comment by pluser** [comment]
Thanks for the suggestion!
However, I am hesitant to change the annotation key. Especially for the parts that are directly changed by the user, I'm concerned about the possibility of embedding a bug.
Do you have any further suggestions that you think should be changed?

**Comment by fad3t** [comment]
Hi,
I understand this might be tricky to change, that's why I was suggesting to support both for some time — plus this would need to be carefully tested.
I've just started using the controller, so I'll share some more improvements once I'm a bit more experimented ;)

**Comment by pluser** [comment]
Hmmm. I think we can change it for some internal names. But changing the external interface is risky and I would like to keep it as is.

**Comment by fad3t** [comment]
Never mind, this was just a suggestion, it's OK if you don't feel like changing it. Thx for the feedback.
