### ISSUE TITLE
Allow resizing without storage class annotation

### ISSUE THREAD

**Issue by vpedosyuk** [topolvm/pvc-autoresizer#27]
We use GKE and it automatically provisions `standard` storage class:
https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#storageclasses

We already have many PVCs based on the default SC and we'd like to resize them with your magic software (thanks for that!). However, we are unable to manually annotate the SC because we are on the GitOps train. We are also unable to migrate data from existing PVCs onto ones based on a separately created (and properly annotated) SC.

Thus, the question is: is there a possibility to disable the requirement of having SC annotated?

**Comment by llamerada-jp** [comment]
@vpedosyuk 
It is not possible to use pvc-autoresizer without annotations. And you should [enable volume expansion](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/volume-expansion) in addition to the annotations.

**Comment by vpedosyuk** [comment]
@llamerada-jp Thanks for the quick reply. It seems the `standard` GKE storage class has volume expansion enabled by default (not sure whether it's documented somewhere though) so the annotation is the only blocker in our case.

**Comment by ymmt2005** [comment]
@vpedosyuk
We may add an option to skip the annotation checks.
Are you interested in sending such a pull request?

**Comment by ymmt2005** [comment]
Implemented in #29.

**Comment by vpedosyuk** [comment]
@ymmt2005 
Thank you very much for the changes you made.

I have just one last concern: will `pvc-autoresizer` monitor all PVCs in a case when `--no-annotation-check` enabled and when some of the PVCs don't have any annotations set? I mean maybe `resize.topolvm.io/enabled: "true"` makes sense for PVCs as well?

**Comment by ymmt2005** [comment]
No annotations are required for PVCs.
