### ISSUE TITLE
Enable Configuration of Storage Defaults

### ISSUE THREAD

**Issue by josephangbc** [topolvm/pvc-autoresizer#286]
**What should the feature do:**
- Enable Configuration of Defaults for `ResizeThresholdAnnotation`, `ResizeInodesThresholdAnnotation`, `ResizeIncreaseAnnotation` and `StorageLimitAnnotation`
- Allow PVC autoresizing without annotations on PVC. I believe when PVC does not have `StorageLimitAnnotation`, `PvcStorageLimit` function returns `0`, after which `isTargetPVC` function returns false, resulting in PVC being skipped in `pvcAutoresizer`.`reconcile` function

**What is use case behind this feature:**
We are using this awesome project to enable resizing of Spark PVCs dynamically. Currently, feature of adding annotations to PVCs via Spark Confs is only available in Spark v4 ([Spark Conf Reference](https://github.com/apache/spark/blob/95b2d27079c2e012ab5bfb8c1dd83b11d7848258/docs/running-on-kubernetes.md#:~:text=spark.kubernetes.executor.volumes.%5BVolumeType%5D.%5BVolumeName%5D.annotation.%5BAnnotationName%5D))

Additionally, currently, we do not have the requirement to configure individual PVCs, thus would like to configure the defaults at pvc-autoresizer level.

Draft Pull Request #287

**Comment by toshipp** [comment]
similar to #82, #86

**Comment by toshipp** [comment]
We've encountered similar issues before and felt that implementing them would add unnecessary complexity, so we decided against it. However, it might be time to revisit this decision.

By the way, are you familiar with the downstream project https://github.com/kubesphere/pvc-autoresizer? It allows you to set a default storage limit for each StorageClass, which might be a solution for your situation.
