### ISSUE TITLE
Drop `resources.limits.storage` support

### ISSUE THREAD

**Issue by toshipp** [topolvm/pvc-autoresizer#35]
## What

We have the ability to specify storage limit by annotation thanks to #32 instead of using `resources.limits.storage`.
Many options confuse users and `resources.limits.storage` can not be updated, so I want to drop the option.
We need to study our use case and build a migration plan because this introduces a breaking change.

## How

Delete code using  `resources.limits.storage`.
Update the usage example in [README.md](https://github.com/topolvm/pvc-autoresizer/blob/main/README.md#how-to-use).

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by tylerauerbeck** [comment]
Is there any date or version planned to drop this support?

**Comment by toshipp** [comment]
I have no plan yet. BTW, before dropping the feature, we will deprecate it first.

**Comment by tylerauerbeck** [comment]
That makes sense. It just seems to have been noted as deprecated already, so wasn't sure where things are in that process.

**Comment by toshipp** [comment]
ah, I missed it had been deprecated. I do not desire to drop it now, I expect that it can be used for a while.
