### ISSUE TITLE
StorageClass level rules

### ISSUE THREAD

**Issue by f10atin9** [topolvm/pvc-autoresizer#82]
**What should the feature do:**
Can autoresizer support the creation of StorageClass level rules? When I set the `threshold`, `storage_limit` and `increase` in StorageClass, I hope that all PVCs of this StorageClass can folloiw  this rule.
**What is use case behind this feature:**
You know that it is not very convenient to set annotations for each PVC. Sometimes the automatically created PVC is easy to be forgotten to set annotations, especially when there are a lot of PVCs.

**Comment by f10atin9** [comment]
BTW，I cannot join slack using the provided link.
> This email address does not appear to be tied to a topolvm account.

**Comment by f10atin9** [comment]
If necessary, I am willing to complete this part of the code.

**Comment by satoru-takeuchi** [comment]
@f10atin9 Could you tell me your email address? I'll try to invite you.

**Comment by f10atin9** [comment]
> @f10atin9 Could you tell me your email address? I'll try to invite you.

Thank you so much, my email is ` f10atin9@qq.com ` .

**Comment by satoru-takeuchi** [comment]
@f10atin9 I failed to invite you via slack's invitation email and sent a invitation link to your email address.Please see your mailbox.

**Comment by f10atin9** [comment]
> I failed to invite you via slack's invitation email and sent a invitation link to your email address.Please see your mailbox.

Thank you for your invitation, I received the email, I have already joined through another mailbox.

**Comment by toshipp** [comment]
@f10atin9 
I consider StorageClass default behavior introduces some complications. For example, if users want to disable auto-resizing for specific PVCs, we need to implement filter logic. And also, I prefer explicit rather than implicit.
I assume your use case is resolved by some other controllers such as OPA mutating admission.

**Comment by f10atin9** [comment]
> @f10atin9 I consider StorageClass default behavior introduces some complications. For example, if users want to disable auto-resizing for specific PVCs, we need to implement filter logic. And also, I prefer explicit rather than implicit. I assume your use case is resolved by some other controllers such as OPA mutating admission.

How about adding an `enable-global-rule` annotation to StorageClass? 
If there is a special PVC in a StorageClass, set `enable-global-rule: false` so that user can set rules for each PVC in this storageclass as before. 
I think that the same set of rules can be used in more cases, and there are fewer cases of special pvc.

**Comment by toshipp** [comment]
I think it's not good.
In our use case, many different workloads use the same SC, so there is a wide variety of resizing policies. It is easy to support such use case by per PVC configuration.
A global configuration can be achieved by other tools as I wrote before, if so, we can keep pvc-autoresizer simple and clean.

**Comment by f10atin9** [comment]
> I think it's not good. In our use case, many different workloads use the same SC, so there is a wide variety of resizing policies. It is easy to support such use case by per PVC configuration. A global configuration can be achieved by other tools as I wrote before, if so, we can keep pvc-autoresizer simple and clean.

Okay i see, thanks for your advice.  😁
