### ISSUE TITLE
Automatically restart deployment

### ISSUE THREAD

**Issue by f10atin9** [topolvm/pvc-autoresizer#83]
**What should the feature do:**
Some storage classes only support offline expansion, which means that users need to stop pods during the resizing process, which is not automatic enough.
**What is use case behind this feature:**
After adding this feature, even if it is a storage class that only supports offline expansion, users do not need to restart pods manually.

**Comment by f10atin9** [comment]
If necessary, I am willing to complete this part of the code.

**Comment by llamerada-jp** [comment]
I hesitate to add this feature. This feature introduces the complicated
control of pod restart that depends on the workload. I want to keep pvc-autoresizer as simple as possible.

**Comment by f10atin9** [comment]
> I hesitate to add this feature. This feature introduces the complicated control of pod restart that depends on the workload. I want to keep pvc-autoresizer as simple as possible.

I understand what you mean, and what about this one?  #82 
And how can I join Slack?
