### ISSUE TITLE
Add option to resize all pvc's in cluster without annotations.

### ISSUE THREAD

**Issue by eugen-korentsov** [topolvm/pvc-autoresizer#86]
Hi,
It would be great to have such an option, to resize all pvc's in the cluster without annotations.
So we can set in  1 place options like threshold and increase in % without storage limit. 

To exclude not-needed volumes, some blacklists can be added. 

I faced already several times with an issue when the operator removes annotations from pvc's. For example, https://github.com/strimzi/strimzi-kafka-operator doing this.

**Comment by toshipp** [comment]
It is similar to #82. We think it introduces some complications, so I recommend reporting an issue to the operator.
