### ISSUE TITLE
Add (or expand metric) to include information on volume that has been resized

### ISSUE THREAD

**Issue by tylerauerbeck** [topolvm/pvc-autoresizer#90]
In addition to all of the `*_total` metrics that are included, it would be useful to have individual metrics for specific volumes to be able to gather information on how many times a specific volume has been resized or has failed to resize. So rather than just seeing that we have X number of resized volumes over a period of time, we can see that volume-xyz has been resized X times over a period of time (which would help us potentially identify some other issue or tell us that we should ensure we have enough storage to cover growth, etc.)

**Comment by toshipp** [comment]
Sound good. If you send a PR, we will review it.
