### ISSUE TITLE
Info: Created an alternative to this autoresizer

### ISSUE THREAD

**Issue by AndrewFarley** [topolvm/pvc-autoresizer#97]
Hey folks, I created a similar service to this, as I couldn't find this service which someone on Reddit pointed me towards and felt like there is/was a huge gap in this field for this tool.  After reviewing the code here, if I understand correctly this service wouldn't handle some of the situations I've encountered when trying to autoscale volumes (eg: scaling up an 1GB disk, by "10%" wouldn't actually trigger Kubernetes to do anything, so you'd need to implement a feature for "min-increase-size") which is implemented on my version below.

If anyone is unable to use this service, or unhappy with this service, or maybe is scared from coding/tweaking things in Go feel free to check this other one out which I wrote in Python.

https://github.com/DevOps-Nirvana/Kubernetes-Volume-Autoscaler

BTW: Much love to any author(s)/contributors here, great minds think alike!  I just added some linking to this repo from my repo's README as well so folks know about an alternative to explore.  Cheers!

**Comment by AndrewFarley** [comment]
After a brief look at the code and docs, I believe the differences between our services are

**Pros to my controller:** 
- Be able to handle tiny volume by having a minimum scale-up increment (which is currently 1GB), customizable globally or per-pvc with an annotation.  I found this issue early-on in my work because I try to minimize cost for my customers.
- Because of the "time-window" feature of mine, it helps prevent accidental scaling-upwards of volumes with services that randomly burst disk usage up and then clean up after.  The current time window is 5, 60-second windows must be in alarm before it scales up.  Useful for services which do bulk-processing of things on an PVC.  All customizable globally or per-pvc with an annotation.
- Automatically waits the specified/correct amount of time in-between provider-based timeouts between attempts to scale a volume.  Defaults to 6h which is the AWS required time-between-resizes allowed, customizable globally or per-pvc with an annotation
- Slack notifications built-in, customizable globally
- Sends events that this autoscaler performs to the Kubernetes events stream for easier debugging for K8s admins
- Able to auto-detect Prometheus if in the same namespace as Prometheus, of course can specify its hostname though
- Much easier to maintain as a community (very simple and easy to code/support/tweak Python code which a larger percentage of DevOps folks especially know)
- Filter what volumes to use based on an prometheus label selector (eg: allows to skip volumes from certain namespaces, or names, etc)

**Pros of your controller in contrast:** 
- Prometheus metrics (great idea though)
- Testing in the codebase
- Automated testing
- Automated build/release via CI/CD

If desired, totally steal some of the ideas I've implemented in mine above, like being able to specify what prometheus label selectors to grab PVCs from.  I've found that really useful to whitelist or blacklist certain volumes eg: blacklist ones that are temporary in nature and don't need to scale.

**Comment by llamerada-jp** [comment]
Thank you for sharing. I close this issue because it is not bug.
